<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AllTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6c0c6f98-e13c-4c0c-92f4-2c31c0a4d3d3</testSuiteGuid>
   <testCaseLink>
      <guid>37271518-0db0-445e-9bf8-03668c842dd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CreateAccount/CreateAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6b451fa5-5ba9-44d9-b9f3-d23385037347</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CreateAccount/CreateAccountInvalid</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>1ce6aebd-a567-4e65-94ff-df2b2d4b0fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8be7db2c-4b17-445c-ad92-deb7b581232b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordConfirm</value>
         <variableId>a43681f5-d4cb-41bf-ac48-1b3ab0faa9f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>error</value>
         <variableId>2cdbc8d7-869b-406a-b21b-9a94a419b04b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8d9d4af-1cbb-4067-8d65-2a7ce61b3889</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>privacyPolicy</value>
         <variableId>aeaa8c3b-341b-478e-bc00-acf26a3c8077</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81e95e82-389a-40a1-ac68-718f5e48cd9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BuyProduct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
