<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>47fc4765-41e8-4956-9417-61e822674870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-links']/ul/li[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu.dropdown-menu-right > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3861b75d-6c25-435b-8077-fd425f78f18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://opencart.abstracta.us:443/index.php?route=account/register</value>
      <webElementGuid>6d1c30ee-d4f9-4f7e-af70-91a1a633dd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>f242fab8-b8b7-4987-a017-a9110f573fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-links&quot;)/ul[@class=&quot;list-inline&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-right&quot;]/li[1]/a[1]</value>
      <webElementGuid>ab02eb00-6206-4d3b-baf6-465f8ec4caca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-links']/ul/li[2]/ul/li/a</value>
      <webElementGuid>210b7d67-f9d4-409f-9070-bb27fcb4515f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>46ff248b-9ee9-42ca-b116-1b5422e0436b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://opencart.abstracta.us:443/index.php?route=account/register')]</value>
      <webElementGuid>af2e548a-50f9-4e49-95e8-1b82adfa3178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>078367f0-014f-4df9-b92e-f1108270b379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://opencart.abstracta.us:443/index.php?route=account/register' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>1efa2d42-a93a-4681-99df-76a10521e001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
