<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirm</name>
   <tag></tag>
   <elementGuidId>05a64d28-0291-44d9-989a-e08a2fdbc82c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e650b488-dc1a-474d-b6c7-6f19592bb1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3ca5d397-459e-4829-9447-5139ddb02e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>343d1c23-5827-4abf-93db-5bc4790a38d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password Confirm</value>
      <webElementGuid>91aebe4c-725c-4171-af85-22c221b5f891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-confirm</value>
      <webElementGuid>aaf452f9-d728-4b2a-8f97-283998c5f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5fb76a24-cead-426a-aa60-c8c71fa6b7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-confirm&quot;)</value>
      <webElementGuid>3da0cd79-b800-4e58-bfd8-ae04fb62a194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-confirm']</value>
      <webElementGuid>ac83ccb7-ccea-4f2f-9323-c1b971ccf49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/fieldset[2]/div[2]/div/input</value>
      <webElementGuid>1c75f36e-551d-44c0-aba2-448c42b000c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[2]/div/input</value>
      <webElementGuid>7e987ea7-3742-4be5-9cd7-c04bc8b2a8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm' and @placeholder = 'Password Confirm' and @id = 'input-confirm']</value>
      <webElementGuid>3fb3b59c-d9a7-4f5a-8e63-982c0091be36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
